# Generated by Django 3.2.2 on 2021-05-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=30)),
                ('dealer_address', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'CarDealer',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('gen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Car Model',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_quantity', models.IntegerField()),
                ('quantity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='webapp.car')),
            ],
            options={
                'verbose_name_plural': 'Quantity',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.IntegerField()),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='webapp.car')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mileage', models.IntegerField()),
                ('mileage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='webapp.car')),
            ],
            options={
                'verbose_name_plural': 'Mileage',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='webapp.car')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='webapp.carmodel'),
        ),
    ]
