# Generated by Django 3.2.2 on 2021-05-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarDealer',
        ),
    ]
